[package]
name = "bookmark-r"
version = "0.1.0"
edition = "2024"
[dependencies]
clap = { version = "4.5.55", features = ["derive"] }
uuid = { version = "1.6", features = ["v4", "serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

tokio = { version = "1.49.0", features = ["full"] }
reqwest = { version = "0.13.1", default-features = false, features = ["json", "rustls"] }

scraper = "0.25.0"

anyhow = "1.0.100"
chrono = { version = "0.4.43", features = ["serde"] }
regex = "1.12.2"
indicatif = "0.18.3"
url = "2.5.8"